const char pageWeb[] =
"<!DOCTYPE html>"
"<html>"
"<body> "
"  <form name=\"input\" method=\"get\">"
"    <div>Insertar pensionado</div>"
"    <select id=\"modoWrite\">"
"      <option value=\"new\">New</option>"
"      <option value=\"overwrite\">Overwrite</option>"
"      <option value=\"check\">New with check</option>"
"    </select>"
""
"    <div>ID pensionado</div>"
"    <input id=\"idUser\" type=\"text\" value = \"00000000\" maxlength = 8>"
"    <div id=\"error\" ></div>"
""
"    <div>Vigencia</div>"
"    <select id=\"vigencia\">"
"      <option value=\"activo\">Vigente</option>"
"      <option value=\"terminada\">Terminada</option>"
"    </select>"
"    <div>"
""
"    <div>Enviar informacion</div>"
"    <button name=\"TP\" onclick=\"enviar_datos(this);\"> Send </button>"
"    <input name=\"TA\" type=\"submit\" value=\"TOGGLE RELAY A\">"
"  </form>"
""
"<script type=\"text/javascript\">"
"function enviar_datos(obj){"
"  var textoSend = \"\";"
"  var textoID = document.getElementById('idUser').value;"
""
"  if(textoID.length != 8){"
"    document.getElementById('idUser').innerHTML = \"Incomplete\";"
"    return;"
"  }"
""
"  textoSend += document.getElementById('modoWrite').selectedIndex+1;"
"  textoSend += textoID;"
"  textoSend += document.getElementById('vigencia').selectedIndex == 1? 0:1; "
"  obj.value = textoSend;"
"  alert(\"Enviando\" + obj.value);"
"} "
"</script>"
"</body>"
"</html>"
;